apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-mongoexpress-deployment
spec:
  selector:
    matchLabels:
      app: k8s-mongoexpress-deployment
  template:
    metadata:
      labels:
        app: k8s-mongoexpress-deployment
    spec:
      containers:
      - name: k8s-mongoexpress-deployment
        image: mongo-express
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
                secretKeyRef:
                  name: k8s-mongodb-secret
                  key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
                secretKeyRef:
                  name: k8s-mongodb-secret
                  key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
                configMapKeyRef:
                  name: k8s-mongodb-configmap
                  key: database-url
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-mongoexpress-service
spec:
  selector:
    app: k8s-mongoexpress-deployment
  type: LoadBalancer  # make it an external service
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30000 # port where external ip will be open - range 30k-32k
