apiVersion: apps/v1

kind: Deployment
metadata:
  name: k8s-mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-mongodb-deployment
  template:
    metadata:
      labels:
        app: k8s-mongodb-deployment
    spec:
      containers:
      - name: k8s-mongodb-deployment
        image: mongo
        resources:
          limits:
            memory: "512Mi"
            cpu: "600m"
        ports:
        - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: k8s-mongodb-secret
                key: mongo-root-username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: k8s-mongodb-secret
                key: mongo-root-password
          
---
apiVersion: v1

kind: Service
metadata:
  name: k8s-mongodb-service
spec:
  selector:
    app: k8s-mongodb-deployment  # match pod/container name above
  ports:
  - protocol: TCP
    port: 27017 # match pod/container port above
    targetPort: 27017 
    