apiVersion: apps/v1

kind: Deployment
metadata:
  name: k8s-nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-nginx-deployment
  template:
    metadata:
      labels:
        app: k8s-nginx-deployment
    spec:
      containers:
      - name: k8s-nginx-deployment
        image: nginx:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
